language: java
jdk: oraclejdk11
install: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "youssefhamza80"
    token: ${SONAR_TOKEN}
services:
  - docker

before_install:
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- cd ConnectedVehicles-APIGateway
- docker build -t "$DOCKER_USERNAME"/cv_apigateway:$TRAVIS_BUILD_ID .
- docker push "$DOCKER_USERNAME"/cv_apigateway:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-ConfigServer
- docker build -t "$DOCKER_USERNAME"/cv_configserver:$TRAVIS_BUILD_ID .
- docker push "$DOCKER_USERNAME"/cv_configserver:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Discovery
- docker build -t "$DOCKER_USERNAME"/cv_discovery:$TRAVIS_BUILD_ID .
- docker push "$DOCKER_USERNAME"/cv_discovery:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Customer
- docker build -t "$DOCKER_USERNAME"/cv_customer:$TRAVIS_BUILD_ID .
- docker push "$DOCKER_USERNAME"/cv_customer:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Vehicle
- docker build -t "$DOCKER_USERNAME"/cv_vehicle:$TRAVIS_BUILD_ID .
- docker push "$DOCKER_USERNAME"/cv_vehicle:$TRAVIS_BUILD_ID

notifications:
  email:
    recipients:
    - yousif.kamal@gmail.com
    on_success: never
    on_failure: always