sudo: required
language: java
jdk: oraclejdk11
install: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "youssefhamza80"
    token: ${SONAR_TOKEN}
    
script:
#- cd ConnectedVehicles-APIGateway
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#- sonar-scanner
#- cd ../ConnectedVehicles-ConfigServer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Discovery
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Customer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Vehicle
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
notifications:
  email:
    recipients:
    - yousif.kamal@gmail.com
    on_success: always
    on_failure: always