sudo: required
language: java
jdk: oraclejdk11
install: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: YoussefHamza
    token:
      secure: fabd841f9349d317c86651546f113cfa421ea446
script:
- cd ConnectedVehicles-APIGateway
- mvn clean install -DskipTests
- sonar-scanner
- cd ../ConnectedVehicles-ConfigServer
- mvn clean install -DskipTests
- sonar-scanner
- cd ../ConnectedVehicles-Discovery
- mvn clean install -DskipTests
- sonar-scanner
- cd ../ConnectedVehicles-Customer
- mvn clean install -DskipTests
- sonar-scanner
- cd ../ConnectedVehicles-Vehicle
- mvn clean install -DskipTests
- sonar-scanner
notifications:
  email:
    recipients:
    - yousif.kamal@gmail.com
    on_success: always
    on_failure: always