sudo: required
language: java
jdk: oraclejdk11
install: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "youssefhamza80"
    token: ${SONAR_TOKEN}
services:
  - docker

before_install:
  - docker login -u=yousifkamal -p=${DOCKER_PASSWORD};
    
script:
#- cd ConnectedVehicles-APIGateway
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- cd ConnectedVehicles-APIGateway
- docker build -t yousifkamal/cv_apigateway:$TRAVIS_BUILD_ID .
- docker push yousifkamal/cv_apigateway:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-ConfigServer
- docker build -t yousifkamal/cv_configserver:$TRAVIS_BUILD_ID .
- docker push yousifkamal/cv_configserver:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Discovery
- docker build -t yousifkamal/cv_discovery:$TRAVIS_BUILD_ID .
- docker push yousifkamal/cv_discovery:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Customer
- docker build -t yousifkamal/cv_customer:$TRAVIS_BUILD_ID .
- docker push yousifkamal/cv_customer:$TRAVIS_BUILD_ID

- cd ../ConnectedVehicles-Vehicle
- docker build -t yousifkamal/cv_vehicle:$TRAVIS_BUILD_ID .
- docker push yousifkamal/cv_vehicle:$TRAVIS_BUILD_ID

#- sonar-scanner
#- cd ../ConnectedVehicles-ConfigServer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Discovery
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Customer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Vehicle
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
notifications:
  email:
    recipients:
    - yousif.kamal@gmail.com
    on_success: always
    on_failure: always