sudo: required
language: java
jdk: oraclejdk11
install: true

script: 
    - mvn clean install -Dskiptests
notifications:
  email:
    recipients:
      - yousif.kamal@gmail.com
    on_success: always # default: change
    on_failure: always # default: always    
