sudo: required
language: java
jdk: oraclejdk11
install: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "youssefhamza80"
    token: ${SONAR_TOKEN}
services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    
script:
#- cd ConnectedVehicles-APIGateway
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- cd ConnectedVehicles-APIGateway
- docker build -t "$DOCKER_USERNAME"/cv_apigateway .
- docker push "$DOCKER_USERNAME"/cv_apigateway

- cd ../ConnectedVehicles-ConfigServer
- docker build -t "$DOCKER_USERNAME"/cv_configserver .
- docker push "$DOCKER_USERNAME"/cv_configserver

- cd ../ConnectedVehicles-Discovery
- docker build -t "$DOCKER_USERNAME"/cv_discovery .
- docker push "$DOCKER_USERNAME"/cv_discovery

- cd ../ConnectedVehicles-Customer
- docker build -t "$DOCKER_USERNAME"/cv_customer .
- docker push "$DOCKER_USERNAME"/cv_customer

- cd ../ConnectedVehicles-Vehicle
- docker build -t "$DOCKER_USERNAME"/cv_vehicle .
- docker push "$DOCKER_USERNAME"/cv_vehicle

- cd ../ConnectedVehicles-MonitoringDashboard
- docker build -t "$DOCKER_USERNAME"/cv_monitoring_app .
- docker push "$DOCKER_USERNAME"/cv_monitoring_app

#- sonar-scanner
#- cd ../ConnectedVehicles-ConfigServer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Discovery
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Customer
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
#- cd ../ConnectedVehicles-Vehicle
#- mvn clean -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=youssefhamza80_ConnectedVehicles
#- sonar-scanner
notifications:
  email:
    recipients:
    - yousif.kamal@gmail.com
    on_success: never
    on_failure: always